version: '3.9'
services:
  backend:
    image: latronico96/pasteleria-backend:latest
    container_name: pasteleria-backend
    ports:
      - "8005:8005"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://database:3306/recetario?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=rootpassword
    depends_on:
      - database
    restart: unless-stopped

  frontend:
    image: latronico96/pasteleria-frontend:latest
    container_name: pasteleria-frontend
    ports:
      - "80:80"
    environment:
      - REACT_APP_API_URL=http://localhost:8080/api
    depends_on:
      - backend
    restart: unless-stopped

  database:
    image: latronico96/mysql:8
    container_name: pasteleria-database
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: recetario
      MYSQL_USER: user
      MYSQL_PASSWORD: userpassword
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 500M
          cpus: '0.5'


volumes:
  mysql_data:
    driver: local
