version: '3.9'
services:
  backend:
    image: latronico96/pasteleria-backend:latest # Imagen del backend
    container_name: pasteleria-backend
    ports:
      - "8080:8080" # Mapea el puerto 8080 del contenedor al 8080 del host
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://database:3306/recetario?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=rootpassword
    depends_on:
      - database
    restart: unless-stopped

  frontend:
    image: latronico96/pasteleria-frontend:latest # Imagen del frontend
    container_name: pasteleria-frontend
    ports:
      - "80:80" # Mapea el puerto 80 del contenedor al 80 del host
    environment:
      - REACT_APP_API_URL=http://localhost:8080/api # URL del backend
    depends_on:
      - backend
    restart: unless-stopped

  database:
    image: latronico96/mysql:8 # Imagen personalizada de MySQL
    container_name: pasteleria-database
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword # Contraseña de root
      MYSQL_DATABASE: recetario       # Nombre de la base de datos
      MYSQL_USER: user                   # Usuario adicional
      MYSQL_PASSWORD: userpassword       # Contraseña para el usuario adicional
    volumes:
      - mysql_data:/var/lib/mysql # Volumen persistente para datos de MySQL
    ports:
      - "3306:3306" # Puerto de MySQL
    restart: unless-stopped

volumes:
  mysql_data:
    driver: local
