services:
  backend:
    env_file:
      - .env
    build:
      context: ./backend
      dockerfile: Dockerfile
      args:
        GITHUB_USERNAME: ${GITHUB_USERNAME}
        GITHUB_PAT: ${GITHUB_PAT}
        SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
        SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
        SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
    environment:
      - SPRING_DATASOURCE_URL=${SPRING_DATASOURCE_URL}
      - SPRING_DATASOURCE_USERNAME=${SPRING_DATASOURCE_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
    container_name: pasteleria-backend
    ports:
      - "8005:8005"
    depends_on:
      - database
    restart: unless-stopped

  frontend:
    env_file:
      - .env
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        REACT_APP_API_URL: ${REACT_APP_API_URL}
    environment:
      - REACT_APP_API_URL=${REACT_APP_API_URL}
    container_name: pasteleria-frontend
    ports:
      - "8081:80"
    depends_on:
      - backend
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 512M

  database:
    env_file:
      - .env
    image: latronico96/mysql:8
    container_name: pasteleria-database
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: recetario
      MYSQL_USER: user
      MYSQL_PASSWORD: userpassword
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 500M
          cpus: '0.5'

volumes:
  mysql_data:
    driver: local
