services:
  backend:
    env_file:
      - .env
    build:
      context: ./backend
      dockerfile: Dockerfile
      args:
        GITHUB_USERNAME: ${GITHUB_USERNAME}
        GITHUB_PAT: ${GITHUB_PAT}
        SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
        SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
        SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
    ports:
      - "8005:8005"
    environment:
      - GITHUB_USERNAME=${GITHUB_USERNAME}
      - GITHUB_PAT=${GITHUB_PAT}
      - SPRING_DATASOURCE_URL=${SPRING_DATASOURCE_URL}
      - SPRING_DATASOURCE_USERNAME=${SPRING_DATASOURCE_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
    depends_on:
      - database
    networks:
      - mynetwork

  frontend:
    env_file:
      - .env
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        GITHUB_USERNAME: ${GITHUB_USERNAME}
        GITHUB_PAT: ${GITHUB_PAT}
        REACT_APP_API_URL: ${REACT_APP_API_URL}
    environment:
      - REACT_APP_API_URL=${REACT_APP_API_URL}
    ports:
      - "80:3000"
    depends_on:
      - backend
    networks:
      - mynetwork

  database:
    env_file:
      - .env
    image: mysql:8
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: recetario
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      retries: 5
    networks:
      - mynetwork
    volumes:
      - mysql_data:/var/lib/mysql
    deploy:
      resources:
        limits:
          memory: 500M
          cpus: '0.5'

networks:
  mynetwork:
    driver: bridge

volumes:
  mysql_data:
    driver: local
