services:
  backend:
    build:
      context: ../hub
      args:
        ENVIRONMENT: development
    image: ""
    volumes:
      - ../hub:/app:cached
      - ../hub/.flake8:/app/.flake8
      - ../hub/.pylintrc:/app/.pylintrc
    command: python manage.py runserver 0.0.0.0:8000
    environment:
      DJANGO_DATABASES_PATH: /app/db.sqlite3
      DJANGO_STATIC_FRONTEND_URL: http://localhost:3000
      DJANGO_REDIS_SERVER: redis://redis:6379/
      REDIS_HOST: redis
    ports:
      - "8000:8000"
    working_dir: /app


  celery:
    build:
      context: ../hub
      args:
        ENVIRONMENT: development
    image: ""
    volumes:
      - ../hub:/app:cached
      - ../hub/.flake8:/app/.flake8
      - ../hub/.pylintrc:/app/.pylintrc
    command: celery -A hub worker --loglevel=info
    environment:
      DJANGO_DATABASES_PATH: /app/db.sqlite3
      DJANGO_REDIS_SERVER: redis://redis:6379/
      REDIS_HOST: redis
      PYTHONPATH: /app
    working_dir: /app

  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile.dev
      args:
        REACT_APP_API_URL: http://localhost:8000
        ENVIRONMENT: development
    image: ""
    ports:
      - "3000:3000"
    environment:
      - ENVIRONMENT=development
      - REACT_APP_API_URL=http://localhost:8000
      - CHOKIDAR_USEPOLLING=true
    command: npm run dev
    volumes:
      - ../frontend:/app
      - /app/node_modules

