version: '3.8'

services:
  backend:
    image: latronico96/hub-backend:latest
    command: sh -c "python manage.py migrate --noinput && gunicorn hub.wsgi:application --bind 0.0.0.0:8000"
    restart: unless-stopped
    volumes:
      - sqlite_data:/data
    environment:
      DJANGO_SETTINGS_MODULE: hub.settings
      DJANGO_DATABASES_PATH: /data/db.sqlite3
      DJANGO_STATIC_FRONTEND_URL: http://recetascocol.com.ar
      DJANGO_REDIS_SERVER: redis://redis:6379/
      REDIS_HOST: redis
    ports:
      - "8000:8000"
    depends_on:
      - redis

  celery:
    image: latronico96/hub-backend:latest
    command: celery -A hub worker --loglevel=info
    restart: unless-stopped
    volumes:
      - sqlite_data:/data
    environment:
      DJANGO_SETTINGS_MODULE: hub.settings
      DJANGO_DATABASES_PATH: /data/db.sqlite3
      DJANGO_STATIC_FRONTEND_URL: http://recetascocol.com.ar
      DJANGO_REDIS_SERVER: redis://redis:6379/
      REDIS_HOST: redis
    depends_on:
      - redis

  redis:
    image: redis:7
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  frontend:
    image: latronico96/frontend:latest
    environment:
      - REACT_APP_API_URL=http://recetascocol.com.ar:8000
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  sqlite_data:
  redis_data:
