services:
  backend:
    build:
      args:
        ENVIRONMENT: production
    image: latronico96/hub-backend:latest
    command: sh -c "python manage.py migrate --noinput && gunicorn hub.wsgi:application --bind 0.0.0.0:8000"
    restart: unless-stopped
    environment:
      DJANGO_SETTINGS_MODULE: hub.settings
      DJANGO_DATABASES_PATH: /data/db.sqlite3
      DJANGO_STATIC_FRONTEND_URL: http://recetascocol.com.ar
      DJANGO_REDIS_SERVER: redis://redis:6379/
      REDIS_HOST: redis
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE_PORT: ${DATABASE_PORT}
    volumes:
      - sqlite_data:/data
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - postgresql

  celery:
    build:
      args:
        ENVIRONMENT: production
    image: latronico96/hub-backend:latest
    command: celery -A hub worker --loglevel=info
    restart: unless-stopped
    environment:
      DJANGO_SETTINGS_MODULE: hub.settings
      DJANGO_DATABASES_PATH: /data/db.sqlite3
      DJANGO_STATIC_FRONTEND_URL: http://recetascocol.com.ar
      DJANGO_REDIS_SERVER: redis://redis:6379/
      REDIS_HOST: redis
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE_PORT: ${DATABASE_PORT}
    volumes:
      - sqlite_data:/data
    depends_on:
      - redis
      - postgresql

  redis:
    image: redis:7
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  frontend:
    image: latronico96/frontend:latest
    environment:
      - REACT_APP_API_URL=http://recetascocol.com.ar:8000
    ports:
      - "80:3000"
    depends_on:
      - backend

  postgresql:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  sqlite_data:
  redis_data:
  pg_data:
