version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.Render
      args:
        GITHUB_USERNAME: ${GITHUB_USERNAME}
        GITHUB_PAT: ${GITHUB_PAT}
    ports:
      - "8081:80" # Frontend en el puerto 8081
      - "8005:8005" # Backend en el puerto 8005
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_NAME: mydatabase
      DB_USER: root
      DB_PASSWORD: password
    depends_on:
      db:
        condition: service_healthy
    networks:
      - mynetwork
    container_name: app-container

  db:
    image: mysql:8
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: user
      MYSQL_PASSWORD: userpassword
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -u root -ppassword || exit 1"]
      interval: 10s
      retries: 5
    networks:
      - mynetwork
    restart: always

networks:
  mynetwork:
    driver: bridge

volumes:
  mysql_data:
